### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring.datasource:
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:bootexample;MODE=MySQL
    
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/twitter
    username: tweeter
    password: tweeter



server:
  port: 8090
#configure session timeout
#  session:
#    timeout: 100

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: tweetme
  version: 0.1
  description: tweetme default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}


hotel.service:
  name: 'default profile:'

# http://localhost:8090/h2-console/
spring:
  h2:
    console:
      enabled: true
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
---
spring:
  profiles: dev
  

spring.jpa:
    hibernate.ddl-auto: none